@startuml

package entity{

    abstract Entity{
        - position: Position
        - hp: int
        - passThrought: boolean
        - reward: int
        + getPosition():(int, int, GlobalDirection)
        + setPosition(int direction)
        + setPosition(int x, int y)
        + canPassThrought(): boolean
        + {abstract} draw()
        + behave(GlobalDirection direction): Direction
        + getReward(): int
    }

    class Hero {
        - score: int
        + draw()
    }

    class Monster{
        + draw()
    }

    package behavior{

        class Behavior{

        }

        note left: Class diagram of behavior

    }


}



Hero --|> Entity
Monster --|> Entity
Entity --> "1" Behavior

@enduml