@startuml

title When the player is attacked
autonumber

participant ZelpopGame as z
participant Dungeon as d
participant "maze: Maze" as m
participant "monster: Monster" as e
participant "Behavior" as b
participant Check as check
participant Attack as attack
participant Move as move
participant "h: Hero" as h

z -> d: updateAll()

d -> m: moveEntities()

loop for every monsters in the maze

    m -> e: behave(maze, entity, IDLE)

    e -> b: behave(maze, entity, IDLE)

    b -> check: check(maze, entity)

    check ->

end

@enduml