@startuml
Actor User
User -> Dungeon : The user wants to move to the left
Dungeon -> Maze : MoveHero(Direction d)
Maze -> Entity : behave(Entity e)
Entity -> Behavior : behave(Entity e)
Behavior --> Entity : direction
Entity --> Maze : direction
Maze -> Maze : canMove(Entity e, int x, int y)
alt A wall is blocking the way
    Maze --> Dungeon : false
    Dungeon --> User : No deplacement
end
Maze --> Dungeon : true
Maze -> Entity : setPosition(direction d)
Maze -> Entity : setPosition(int x, int y)
Dungeon --> User : Moving
@enduml