@startuml
InterfaceGraphique -> Dungeon: Demande a change of texture
Dungeon -> Dungeon : updateAll()
 note left
            same thing for Tile
 end note

Dungeon -> Maze : draw()

 loop       looping on al the Entities "toDrawEntity"

	        Maze -> Entity : draw()
            Entity -> SpriteManager : setSprite(int x, int y)
            SpriteManager -> SpriteManager : Changing the CurrentSprite
            SpriteManager -> TextFactory : getHero()
            TextFactory --> SpriteManager : The texture
            SpriteManager --> Entity : The texture
            Entity --> Maze : The texture

 end

Maze --> Dungeon : Retuning all textures changes
Dungeon --> InterfaceGraphique : draw the new texture changes


@enduml