@startuml

package dungeon{

    class Dungeon{

    }

    class Labyrinth{


    }

    package tile{

        class Tile{

        }

        note "Diagramme de classes\ndes cases" as N1

    }

    package character{

        class Character{

        }

        class Hero{

        }

    }

    package labyrinthFactory{

        class LabyrinthFactory{

        }

        class LabyrinthFile{

        }

    }

}

Dungeon "1" -left-> "*" Labyrinth
Dungeon "1" --> "1" LabyrinthFactory
Labyrinth "1" --> "*" Tile
Labyrinth "1" -up-> "*" Character

Hero --|> Character
Dungeon --> "1" Character

LabyrinthFile --|> LabyrinthFactory

@enduml