@startuml

package dungeon{

    class Dungeon{

    }

    class Maze{


    }

    package tile{

        class Tile{

        }

        note "Class diagram of tiles" as N1

    }

    package entity{

        class Entity{

        }

        class Hero{

        }

    }

    package mazeFactory{

        class MazeFactory{

        }

        class MazeFile{

        }

    }

}

Dungeon "1" -left-> "*" Maze: -maze
Dungeon "1" --> "1" MazeFactory: -mazeFactory
Maze "1" --> "*" Tile: -tiles
Maze "1" -up-> "*" Entity: -entities

Hero --|> Entity
Dungeon --> "1" Entity : -hero

MazeFile --|> MazeFactory

@enduml