@startuml

skinparam class {
	BackgroundColor #FFC0CB
	ArrowColor Black
	BorderColor Black
}

package tile{

    class EmptyTile{

    }

    class Wall{

    }

    class Treasure{

    }

    class Trap{

    }

    abstract Effect{

    }

    class TileFabric << (S,#FF7700) Singleton >>{

    }

}

Wall --|> Effect
Effect --|> EmptyTile
Effect --> "1" EmptyTile : -decore
Trap --|> Effect
Treasure --|> Effect

TileFabric ..> EmptyTile : create

@enduml