@startuml

class ZelpopGame{

}

interface Game{

}

package dungeon{

    class Position{

    }

    class Dungeon{
        - currentMaze
        + moveHero(Direction d)
        + generateMaze()
        + generateMaze(File Filename)
        + updateAll()
        + draw()
    }

    class Maze{
        - toDrawEntity: List<Entity>
        - toDrawTile: List<Tile>
        + Maze(List<Tile> tiles, List<Entity> entities)
        + draw()
        + updateEntities()
        + moveEntity(Entity e, Direction d)
        + moveEntity(Entity e)
    }

    package tile{

        class Tile{

        }

        note "Class diagram of tiles" as N1

    }

    package entity{

        abstract Entity{

        }

        class Hero{

        }

        class EntityFactory << (S,#FF7700) Singleton >>{

        }

    }

    class ColisionManager << (S,#FF7700) Singleton >>{
        - {static} instance: ColisionManager
        - ColisionManager()
        + getInstance(): ColisionManager
        + canMove(Entity e, int x, int y): boolean
        + canMove(Entity e1, Entity e2): boolean
        + setMaze(Maze maze)
    }

    ColisionManager --> "1" Maze: -maze

    package mazeFactory{

        interface MazeFactory{
            + {static}getMaze(): Maze
            + {static}getMaze(File fileName)
        }

        class MazeFile{
            - File: fileName
            + getMaze(): Maze
            + getMaze(File fileName)
        }

        class MazeDefault{
            + getMaze(): Maze
            + getMaze(File fileName)
        }

    }

}

class ScaleConstant{
    + {static} getScale(): int
    + {static} getTileWidth(): int
    + {static} getTileHeight(): int
    + {static} getEntityWidth(): int
    + {static} getEntityHeight(): int
}

class TextureFactory{
    + {static}getMonster()
    + {static}getHero()
    + {static}getEmptyTile()
    + {static}getWall()
    + {static}getTrap()
    + {static}getTreasure()
}

class SpriteManager{
    + currentSprite: int
    + SpriteSheet: Image
    + SpriteManager(Image sprite)
    + setSprite(int x, int y)
    + getCurrentSprite(): Image
}

class GlobalSprite{
    + {static} get8Sprite():int
    + {static} get16Sprite():int
}

enum GlobalDirection{
    + {static} UP
    + {static} DOWN
    + {static} LEFT
    + {static} RIGHT
    + {static} IDLE
}

MazeDefault --|> MazeFactory
Dungeon "1" --> "*" Maze: -maze
Dungeon "1" --> "1" MazeFactory: -mazeFactory
Maze "1" --> "*" Tile: -tiles
Maze "1" --> "*" Entity: -entities
Maze --> "*" Position

EntityFactory ..> Entity : create

ZelpopGame ..|> Game
ZelpopGame --> "1" Dungeon: -dungeon

Hero --|> Entity
Dungeon "1" --> "1" Entity : -hero

MazeFile --|> MazeFactory

Tile --> "1" SpriteManager
Entity --> "1" SpriteManager

Position --> "1" Tile: -tile
Position --> "*" Entity: -entity

@enduml