@startuml
title  When passing to another level add defiend amount to monster state
autonumber

participant "ZelpopGame: game" as z
participant InGame as g
participant Dungeon as d
participant "mazeFactory: mf" as mf
participant "ef: entityFactory" as ef
participant "StatFactory" as sf
participant "ss: ScaleStat" as ss


z -> g: evolve(game, LEAVE_LEVEL)

g -> d: changeLevel()

d -> ss: setLevel()

d -> mf: getRandomMaze()

alt depends on monster type here is a ghost
    mf -> ef: getRandomGhost()
    ef -> sf: getGhostStats()
    sf -> ss: scaleStat()
    sf -> sf: new Stats()

end


mf --> d: entities is been updated

d --> g: entities is been updated

g --> z: entities is been updated
@enduml