@startuml

title When the player is attacking, a sound is triggered
autonumber

actor player

participant "InGame: inGame" as g
participant "Sound" as s
participant "AudioClip: attack" as a

player -> g: Want to attack

g -> g: evolve(game, Cmd.ATTACK)

g -> s: getHeroAttack()

s --> g: attack

g -> a : play()


@enduml