@startuml

title When the player wants to attack
autonumber

actor player

participant ZelpopGame as z
participant Dungeon as d
participant "maze: Maze" as m
participant "h: Hero" as h
participant "SpriteManagerEntity" as sme
participant Behavior as b
participant AttackSimple as as
participant "SoundEntity: soundManager" as s


player --> z: The player wants to attack

z -> d: attack()

d -> m: attack()

m -> h: attack(maze)

h -> sme: isAttacking()

h -> b: behave(maze, h, ATTACK)

b -> as: attack(maze, h)

as --> h: isAttacking()

h -> s: playActionSound()

ref over b
    Attack sequence diagram
    for the following
end ref

@enduml