@startuml

title When the player wants to attack
autonumber

actor player

participant "Dungeon: d" as d
participant "Maze: m" as m
participant "SoundDungeon: sound" as s

player -> d: updateAll()

d -> m: moveEntities()

d -> m: regenEntites()

d -> m: playSound()

m -> s: playActionSound()

@enduml