@startuml
Actor User
User -> Dungeon : The user wants to create a maze
Dungeon -> Dungeon : generateMaze(File fileName)
Dungeon -> MazeFactory : getMaze(File fileName)
Loop maze Size
    MazeFactory -> TileFactory : generateTile
    create Tile
    TileFactory -> Tile : new
    TileFactory --> MazeFactory : Tile
    MazeFactory -> EntityFactory : generateEntity
    create Entity
    EntityFactory -> Entity : new
    EntityFactory --> MazeFactory : Entity
end
create Maze
MazeFactory -> Maze : new
Maze -> EntityFactory : getHero()
MazeFactory --> Dungeon : maze
Dungeon --> User : A new maze
@enduml