@startuml
ZelpopGame -> Dungeon : updateAll()
Dungeon -> Maze : moveEntities()


Maze -> Entity : behave(Entity e)
Entity -> Behavior : behave(Entity e)
Behavior --> Entity : direction
Entity --> Maze : direction
Maze -> Maze : canMove(Entity e, int x, int y)
opt Something is blocking the way
Maze -> Entity : setPosition(int x, int y)
end
@enduml