@startuml
User -> Dungeon: The user wants to repaint the frame
Dungeon -> Dungeon : draw()

Dungeon -> Maze : draw()

loop looping on all  entities
    Maze -> Entity : draw()
    Entity -> SpriteManager : setSprite(int x, int y)
    SpriteManager -> SpriteManager : Changing the CurrentSprite
    SpriteManager --> Entity : The sprite to draw

     note left
        The draw method
        will draw the sprite
     end note
end


note right
    The draw method from Maze
    will do the exact same
    thing for the tiles
end note

Dungeon --> User : Drawing


@enduml