@startuml

title How the sound integration works

package sound{

    class Sound{
        + getMonsterAttack(): AudioClip
        + getGoblinAttack(): AudioClip
        + getAmbianceOne(): AudioClip
        + getMenuButton(): AudioClip
        + getHeroAttack(): AudioClip
        + getLowLife(): AudioClip
        + getStairs(): AudioClip
    }

    class SoundEntity{
        - AudioClip: attackSound[0..*]

        + SoundEntity(AudioClip: attackSound[0..*])

        + playActionSound()
        + stopActionSound()
    }


    class SoundTile{
        - AudioClip: actionSound
        + SoundTile(AudioClip: actionSound)

        + playActionSound()
        + stopActionSound()
    }

    class SoundMaze{
        - Timer: task
        - AudioClip: ambianceSound[0..*]

        + SoundMaze(AudioClip: ambianceSound[0..*])

        + playActionSound()
        + stopActionSound()
    }

    interface SoundManager{
        + {abstract} playActionSound()
        + {abstract} stopActionSound()
    }
}
Entity --> "1" SoundEntity: -sound
Tile --> "1" SoundTile: -sound
Maze --> "1" SoundMaze: -sound

SoundEntity ..|> SoundManager
SoundMaze ..|> SoundManager
SoundTile ..|> SoundManager

@enduml